# uv
export PATH="/home/lain/.local/bin:$PATH"
export TERMINAL="alacritty"
export ZDOTDIR="$HOME/.config/zsh"
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export CARGO_HOME="$XDG_DATA_HOME"/cargo 
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export W3M_DIR="$XDG_STATE_HOME/w3m"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv 
export PARALLEL_HOME="$XDG_CONFIG_HOME"/parallel 
export WINEPREFIX="$XDG_DATA_HOME"/wineprefixes/default
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java 
export BROWSER=librewolf
